services:
  mariadb:
    image: mariadb:10.7.3
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    container_name: todo-database
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    restart: always

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8000:${PORT_BACKEND}"
    depends_on:
      - mariadb
    env_file:
      - ./.env
    command: bash -c "
      sh ./start.sh
      && npm start
      "

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:${PORT_FRONTEND}"
    depends_on:
      - backend
    env_file:
      - ./.env
    command: ["npm", "start"]

volumes:
  mariadb-data:
